# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###


# @name create-transcription
POST http://localhost:3333/videos/e551ea33-bc2d-4b7e-9117-196a7f87ac7f/transcription
Content-Type: application/json

{
    "prompt": "clean architecture, ddd"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "2b573c67-06ad-430b-a644-01871ef8bc23",
  "temperature": 0.5,
  "prompt": "Gere um resumo da transcrição do vídeo informada a seguir: '''{transcription}'''"
}